# Setup
title:               'Shanasia Sylman'
tagline:             'Park Planner & PhD Candidate'
description:         'A pesronal website'
url:                 https://shanasia.github.io
baseurl:             /
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              'Shanasia Sylman'
  url:               'https://shanasia.github.io'
  email:             'sgs237@cornell.edu'

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
